# Generated by Django 5.0.1 on 2024-02-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('attractions', models.TextField(verbose_name='Atrações')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('date', models.DateField(verbose_name='Data')),
                ('time_starts', models.TimeField(verbose_name='Hora de Início')),
                ('time_ends', models.TimeField(verbose_name='Hora de Término')),
                ('address', models.CharField(default='default', max_length=255, verbose_name='Endereço')),
                ('min_age', models.IntegerField(verbose_name='Idade Mínima')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('CPF', models.CharField(max_length=14, verbose_name='CPF')),
                ('age', models.IntegerField(verbose_name='Idade')),
                ('gender', models.CharField(max_length=1, verbose_name='Sexo')),
                ('email', models.EmailField(max_length=255, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('events', models.ManyToManyField(to='subscriptions.event')),
            ],
        ),
    ]
